### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by khwang1** [BrianMMcClain/riak-release#4]
We'd like to fork this and add riak-cs support, but there is no license on this repository. Could you add one? Maybe [MIT](http://opensource.org/licenses/MIT)?

**Comment by BrianMMcClain** [comment]
Hi @khwang1, good point, I do seem to be missing that. I am a fan of MIT, but would Apache 2.0 be agreeable as well? The reason I lean that way is that's the license that Riak is release under, as well as all BOSH components and releases, including Cloud Foundry. Feels like it'd fit nicely, do you agree?

**Comment by khwang1** [comment]
Yes, Apache 2.0 would be great. Thank you!

**Comment by BrianMMcClain** [comment]
Awesome, added in 262e174465e3eeeebd7117daa84e9b6692206288
